const actionTypes = {
   FETCH_USER: "FETCH_USER",
   CREATE_USER: "CREATE_USER",
   DELETE_USER: "DELETE_USER",
   UPDATE_USER: "UPDATE_USER",
   FETCH_SINGLE_USER: "FETCH_SINGLE_USER",
   LOGIN_USER: "LOGIN_USER",
   USER_ERROR: "USER_ERROR",
   CREATE_ERROR: "CREATE_ERROR",

   //payments
   CREATE_PAYMENT: "CREATE_PAYMENT",
   FETCH_PAYMENT: "FETCH_PAYMENT",
   UPDATE_PAYMENT: "UPDATE_PAYMENT",
   FETCH_SINGLE_PAYMENT: "FETCH_SINGLE_PAYMENT",

   //current package
   SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
   UPDATE_CURRENT_PAGE: "UPDATE_CURRENT_PAGE",

   //cart
   CREATE_CART: "CREATE_CART",
   DELETE_CART: "DELETE_CART",
   FETCH_CART: "FETCH_CART",

   //category
   CREATE_CATEGORY: "CREATE_CATEGORY",
   FETCH_CATEGORY: "FETCH_CATEGORY",
   DELETE_CATEGORY: "DELETE_CATEGORY",
   UPDATE_CATEGORY: "UPDATE_CATEGORY",

   //sub category
   CREATE_SUB_CATEGORY: "CREATE_SUB_CATEGORY",
   FETCH_SUB_CATEGORY: "FETCH_SUB_CATEGORY",
   DELETE_SUB_CATEGORY: "DELETE_SUB_CATEGORY",
   UPDATE_SUB_CATEGORY: "UPDATE_SUB_CATEGORY",

   // product section
   FETCH_PRODUCT: "FETCH_PRODUCT",
   FETCH_SINGLE_PRODUCT: "FETCH_SINGLE_PRODUCT",
   CREATE_PRODUCT: "CREATE_PRODUCT",
   UPDATE_PRODUCT: "UPDATE_PRODUCT",
   DELETE_PRODUCT: "DELETE_PRODUCT",
};

export default actionTypes;
